default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: db
  username: user
  password: password
  database: mydatabase
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>